name: Auto Commit
on:
  schedule:
    - cron: '0 14 * * *' # 한국 시간(KST) 오후 11시 실행 (UTC 14시)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "kivica"
          git config --global user.email "kivicls@gmail.com"

      - name: Ensure working directory is clean
        run: |
          git reset --hard
          git clean -fd
          git pull --rebase origin main || true

      - name: Create or update log file to trigger commit
        run: |
          echo "Last commit: $(date)" > .github/last_commit.log
          git add .github/last_commit.log

      - name: Auto commit and push
        run: |
          git commit -m "Automated commit: $(date)" || true
          git push origin main || true
