name: Auto Commit
on:
  schedule:
    - cron: '0 14 * * *' # UTC 14:00 (Every day at 14:00 UTC)

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "kivica"
          git config --global user.email "kivicls@gmail.com"

      - name: Ensure working directory is clean
        run: |
          git reset --hard
          git clean -fd
          git pull --rebase origin main || true

      - name: Modify an existing file to trigger commit
        run: |
          echo "Last commit update: $(date)" >> commit_log.txt
          git add commit_log.txt

      - name: Auto commit and push
        run: |
          git commit -m "Automated commit: $(date)" || echo "No changes to commit"
          git push origin main || echo "
